FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src
# WORKDIR /aPP
COPY *.csproj .
RUN dotnet restore *.csproj
COPY . .
# RUN dotnet publish Tech365Api.csproj -c Release -o out --no-restore

RUN dotnet publish Tech365Api.csproj -c Release -o /app/publish --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
ENV ASPNETCORE_HTTP_PORT=8080
ENTRYPOINT ["dotnet", "Tech365Api.dll"]